import click
import torch
from ..nn import PerformerModel
from ..console import Console
from ..utils import progress
from .middleware import ClickMiddleware as M
from ..io import FileIO


@click.command(context_settings={'show_default': True})
@click.argument('model', type=click.Path(exists=True, file_okay=True, dir_okay=False, resolve_path=True))
@click.argument('output', default='out.csv', type=click.Path(file_okay=True, dir_okay=False))
@click.option('--tokens', '-n',  default=100, help='Number of tokens to generate.')
@M.seed()
@M([
    ('model', '.pt'),
    ('output', *FileIO.EXT)
], device='cpu').wrapper
def gen(**params):
    """Given a path to a pre-trained (`.pt`) **MODEL**, it writes an **OUTPUT** file with sequential data generated by the model auto-regressively—i.e., feeding the output back as input. 
    The generated data can be written in any of the following formats: `.txt`, `.json`, or `.csv`.
    """
    device = params['device']
    model_path = params['model']
    output = params['output']
    seed = params['seed']

    if seed != 0:
        torch.manual_seed(params['seed'])

    model: PerformerModel = torch.load(f=model_path,
                                       weights_only=False,
                                       map_location=device)
    model.reset()
    model.eval()
    events = []
    num_tokens = params['tokens']
    display = Console.get_display(n_rows=1)
    with torch.no_grad():
        x = torch.randn(1, 1, model.input_layer.output_size, device=device)
        x = model.input_layer(x, inverse=True)
        for i in range(num_tokens):
            display.update(progress=progress(i, num_tokens - 1))
            y = model.step(x)
            events.append(y.clone())
            x = y[..., model.input_mask]

    events = torch.cat(events, dim=1).squeeze(0)

    FileIO.write(events, output, model.temporal)
    Console.success("\nDONE", bold=True)
